### ISSUE TITLE
Add support for Critical-rating

### ISSUE THREAD

**Issue by putsi** [swissfondue/gtta#4]
The current rating-system allows Low/Med/High risk levels. 
Implementation of Critical-risk level would for example make the rating-levels compatible with CVSS-score specification (https://www.first.org/cvss/specification-document#5-Qualitative-Severity-Rating-Scale).

Any comments on this?

**Comment by swissfondue** [comment]
1ts of all: thx a lot for your contributions. Highly appreciated. About rating: yes – it is an ongoing discussing in our pentest team. We had it…then removed it again. Dunno – most clients r ok with 3 ratings…

**Comment by putsi** [comment]
Could it be possible to make it as configurable value (select per project or per GTTA-instance via params.php config)?
This could allow for example following rating levels:
- None/Low/Med/**High** (used for example by your pentest team and [National Vulnerability Database for CVSS V2 ratings](https://nvd.nist.gov/vuln-metrics/cvss))
- None/Low/Med/**High**/**Critical** (used for example by [National Vulnerability Database for CVSS V3 ratings](https://nvd.nist.gov/vuln-metrics/cvss))
- None/Low/Med/**High**/**Critical**/**Urgent** (I think this was/is used by "PCI DSS requirements for ASVs"?).

**Comment by swissfondue** [comment]
Probably would make most sense on a project base --> most clients will be ok with 3 values. A few ones might need 4. So far we talked every client into using our 3 :) But adding a new rating is complex as there are so many dependencies in UI, reporting, graphics, calculations etc. …that’s why we never did it

 

Von: Jarmo Puttonen [mailto:notifications@github.com] 
Gesendet: Donnerstag, 27. April 2017 10:48
An: swissfondue/gtta <gtta@noreply.github.com>
Cc: swissfondue <oliver@muenchow.ch>; Assign <assign@noreply.github.com>
Betreff: Re: [swissfondue/gtta] Add support for Critical-rating (#4)

 

Could it be possible to make it as configurable value (select per project or per GTTA-instance via gtta.ini config)?
This could allow for example following rating levels:

*	None/Low/Med/High (used for example by your pentest team and National Vulnerability Database for CVSS V2 ratings <https://nvd.nist.gov/vuln-metrics/cvss> )
*	None/Low/Med/High/Critical (used for example by National Vulnerability Database for CVSS V3 ratings <https://nvd.nist.gov/vuln-metrics/cvss> )
*	None/Low/Med/High/Critical/Urgent (I think this was/is used by PCI DSS in some point?).

**Comment by putsi** [comment]
Ok. The issue is closed as this won't be implemented for now.

**Comment by anton-belousov** [comment]
@putsi, thank you for your contribution and suggestions!

Just a small note on this - we have a task named "Custom rating categories" in a private JIRA, but it was temporarily postponed for future versions. It perfectly covers the Critical rating suggestion - users will create any number of ratings and name them as they wish. As @swissfondue mentioned, it requires deep code changes, because the current rating system is far from being optimal. Hope someday we (or someone) will implement that.

I will try to move the existing issues to github within next few days - there are 89 planned issues/features in JIRA and it may take a while to properly format them.
